### ISSUE TITLE
Lua JSON library not found

### ISSUE THREAD

**Issue by nabulator** [Hoshikara/Nightfall#9]
Running Ubuntu 18.04 and master branch of USC. 

```
[00:40:07][Error] Lua error: ...-clone/bin/skins/Nightfall/scripts/common/jsonloader.lua:2: module 'lib/JSON' not found:
	no field package.preload['lib/JSON']
	no file '/usr/local/share/lua/5.3/lib/JSON.lua'
	no file '/usr/local/share/lua/5.3/lib/JSON/init.lua'
	no file '/usr/local/lib/lua/5.3/lib/JSON.lua'
	no file '/usr/local/lib/lua/5.3/lib/JSON/init.lua'
	no file './lib/JSON.lua'
	no file './lib/JSON/init.lua'
	no file '/home/user/unnamed-sdvx-clone/bin/skins/Nig
	no file '/usr/local/lib/lua/5.3/lib/JSON.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lib/JSON.so'
```

Looks like something funky with the `package.path`. Probably can submit a PR request once I find the most elegant way to solve this problem.

**Comment by ohmree** [comment]
I'm also getting this error on Arch Linux, with the `unnamed-sdvx-clone` package from the AUR.

EDIT: this seems to be fixed by replacing all occurances of `lib/JSON` with `lib/json`, seems like it's a filename case issue that doesn't happen on windows due to NTFS being case-insensitive.

EDIT #2: now I can launch the game, but once I press the singleplayer button I get an error:
`cannot open /path/to/usc/skins/Nightfall/scripts/songselect/settingswheel.lua: No such file or directory`

**Comment by Nanoblender** [comment]
Changing lib/JSON to lib/json fixed the skin for me, everything works fine now.

**Comment by Hoshikara** [comment]
addressed in https://github.com/Hoshikara/Nightfall/commit/92f02f26d30d9c6f4a29ca2599728069c2dae52d
